/*
  *Created by M.Helal
  *On September 26, 2019
  *Sleep Calculator
 */

public class SleepCalculator extends javax.swing.JFrame {

    public SleepCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterButton = new javax.swing.JButton();
        birthDay = new com.toedter.calendar.JYearChooser();
        presentDay = new com.toedter.calendar.JYearChooser();
        birthYear = new com.toedter.calendar.JYearChooser();
        birthMonth = new com.toedter.calendar.JYearChooser();
        presentYear = new com.toedter.calendar.JYearChooser();
        presentMonth = new com.toedter.calendar.JYearChooser();
        hoursSlept = new javax.swing.JLabel();
        daysAlive = new javax.swing.JLabel();
        sleepGFX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterButton.setBackground(new java.awt.Color(198, 79, 146));
        enterButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        enterButton.setForeground(new java.awt.Color(255, 255, 255));
        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 260, 140, -1));

        birthDay.setToolTipText("Clicking and holding the scroller makes it scroll faster");
        birthDay.setAutoscrolls(true);
        birthDay.setFocusCycleRoot(true);
        birthDay.setMaximum(31);
        birthDay.setRequestFocusEnabled(false);
        birthDay.setYear(1);
        getContentPane().add(birthDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 42, -1));

        presentDay.setToolTipText("Clicking and holding the scroller makes it scroll faster");
        presentDay.setAutoscrolls(true);
        presentDay.setFocusCycleRoot(true);
        presentDay.setMaximum(31);
        presentDay.setRequestFocusEnabled(false);
        presentDay.setYear(1);
        getContentPane().add(presentDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 42, -1));

        birthYear.setToolTipText("Clicking and holding the scroller makes it scroll faster");
        getContentPane().add(birthYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 63, -1));

        birthMonth.setToolTipText("Clicking and holding the scroller makes it scroll faster");
        birthMonth.setAutoscrolls(true);
        birthMonth.setEndYear(12);
        birthMonth.setYear(1);
        getContentPane().add(birthMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 42, -1));

        presentYear.setToolTipText("Clicking and holding the scroller makes it scroll faster");
        getContentPane().add(presentYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 63, -1));

        presentMonth.setToolTipText("Clicking and holding the scroller makes it scroll faster");
        presentMonth.setAutoscrolls(true);
        presentMonth.setEndYear(12);
        presentMonth.setYear(1);
        getContentPane().add(presentMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 42, -1));

        hoursSlept.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        hoursSlept.setForeground(new java.awt.Color(255, 255, 255));
        hoursSlept.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoursSlept.setText("0");
        hoursSlept.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hoursSlept, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 230, 20));

        daysAlive.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        daysAlive.setForeground(new java.awt.Color(255, 255, 255));
        daysAlive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daysAlive.setText("0");
        daysAlive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(daysAlive, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 230, -1));

        sleepGFX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sleepCalcGFX.png"))); // NOI18N
        getContentPane().add(sleepGFX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        // initializing and setting variables
        int dayA = birthDay.getValue();
        int dayB = presentDay.getValue();
        int monthA = birthMonth.getValue();
        int monthB = presentMonth.getValue();
        int yearA = birthYear.getValue();
        int yearB = presentYear.getValue();
        //defining differences
        int dayDiff = dayB - dayA;
        int monthDiff = monthB - monthA;
        int yearDiff = yearB - yearA;
        //calculating day and thus hour difference
        int totalDays = dayDiff + (monthDiff * 30) + (yearDiff * 365);
        int totalHours = totalDays * 8;
        //outputing amount to the user
        daysAlive.setText(String.valueOf(totalDays));
        hoursSlept.setText(String.valueOf(totalHours));

    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SleepCalculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser birthDay;
    private com.toedter.calendar.JYearChooser birthMonth;
    private com.toedter.calendar.JYearChooser birthYear;
    private javax.swing.JLabel daysAlive;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel hoursSlept;
    private com.toedter.calendar.JYearChooser presentDay;
    private com.toedter.calendar.JYearChooser presentMonth;
    private com.toedter.calendar.JYearChooser presentYear;
    private javax.swing.JLabel sleepGFX;
    // End of variables declaration//GEN-END:variables
}
