/*
  *Created by M.Helal
  *On October 18, 2019
  *Powers
 */

public class Powers extends javax.swing.JFrame {

    /**
     * Creates new form Powers
     */
    public Powers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseInput = new javax.swing.JTextField();
        powerInput = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        outputScroll = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        powersGFX = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        baseInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                baseInputKeyPressed(evt);
            }
        });
        getContentPane().add(baseInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 58, -1));

        powerInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                powerInputKeyPressed(evt);
            }
        });
        getContentPane().add(powerInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 59, -1));

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(enterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        outputLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(outputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 340, 20));

        outputArea.setEditable(false);
        outputArea.setBackground(new java.awt.Color(61, 104, 81));
        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        outputArea.setForeground(new java.awt.Color(255, 255, 255));
        outputArea.setRows(5);
        outputArea.setBorder(null);
        outputScroll.setViewportView(outputArea);

        getContentPane().add(outputScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 350, 310));

        powersGFX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/powersGFX.png"))); // NOI18N
        getContentPane().add(powersGFX, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        //initialize variables
        int power, base;
        String powers = "";

        //validate user input
        try {
            base = Integer.parseInt(baseInput.getText());
            power = Integer.parseInt(powerInput.getText());
        } catch (NumberFormatException e) {
            outputLabel.setText("Please enter a whole number base and power.");
            return;
        }

        //further validation
        if (power == 0) {
            outputLabel.setText("Anything to the power of 0 is 1.");
        } else if (power < 0 || power > 10) {
            outputLabel.setText("Please enter an exponent between 1-10.");
        }

        //calculate and loop through powers (1-10)
        for (int i = 1; i <= power && power < 11; i++) {
            powers = powers + base + "^" + i + " = "
                    + (String.valueOf(Math.pow(base, i)) + "\n");
        }

        //display powers to the user
        outputArea.setText(powers);
    }//GEN-LAST:event_enterButtonActionPerformed

    private void baseInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_baseInputKeyPressed
        clearOut();
    }//GEN-LAST:event_baseInputKeyPressed

    private void powerInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_powerInputKeyPressed
        clearOut();
    }//GEN-LAST:event_powerInputKeyPressed

    private void clearOut() {
        //clear all outputs
        outputArea.setText("");
        outputLabel.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Powers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Powers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Powers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Powers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Powers().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField baseInput;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JScrollPane outputScroll;
    private javax.swing.JTextField powerInput;
    private javax.swing.JLabel powersGFX;
    // End of variables declaration//GEN-END:variables
}
